// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmurfApp.Infrastructure;

#nullable disable

namespace SmurfApp.Infrastructure.Migrations
{
    [DbContext(typeof(SmurfDbContext))]
    partial class SmurfDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmurfApp.Domain.Smurf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Smurfs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7bd2c98e-8e90-4f50-9f7e-2fd9b5ce36f0"),
                            Age = 546,
                            Category = 0,
                            ImageUrl = "https://charactersdb.com/wp-content/uploads/papa-smurf-cartoon.jpg",
                            Name = "Papa Smurf"
                        },
                        new
                        {
                            Id = new Guid("d1a1f4b2-3c6b-4f7e-9d1e-3b2c4a5f6e7a"),
                            Age = 101,
                            Category = 0,
                            ImageUrl = "https://charactersdb.com/wp-content/uploads/brainy-smurf-cartoon.jpg",
                            Name = "Brainy Smurf"
                        },
                        new
                        {
                            Id = new Guid("a2b3c4d5-e6f7-4812-9a3b-0c1d2e3f4b5c"),
                            Age = 80,
                            Category = 3,
                            ImageUrl = "https://charactersdb.com/wp-content/uploads/smurfette-cartoon-80s.jpg",
                            Name = "Smurfette"
                        },
                        new
                        {
                            Id = new Guid("f4e3d2c1-b0a9-4876-8f6e-5d4c3b2a1f0e"),
                            Age = 100,
                            Category = 1,
                            ImageUrl = "https://charactersdb.com/wp-content/uploads/hefty-smurf-cartoon.jpg",
                            Name = "Hefty Smurf"
                        },
                        new
                        {
                            Id = new Guid("c3b2a1f0-e9d8-4765-8c7b-6a5d4e3f2b1c"),
                            Age = 100,
                            Category = 2,
                            ImageUrl = "https://charactersdb.com/wp-content/uploads/clumsy-smurf-cartoon.jpg",
                            Name = "Clumsy Smurf"
                        },
                        new
                        {
                            Id = new Guid("9f8e7d6c-5b4a-4321-8e9f-0a1b2c3d4e5f"),
                            Age = 99,
                            Category = 3,
                            ImageUrl = "https://charactersdb.com/wp-content/uploads/vanity-smurf-cartoon.jpg",
                            Name = "Vanity Smurf"
                        },
                        new
                        {
                            Id = new Guid("01234567-89ab-4cde-8fab-0123456789ab"),
                            Age = 160,
                            Category = 2,
                            ImageUrl = "https://charactersdb.com/wp-content/uploads/jokey-smurf-cartoon.jpg",
                            Name = "Jokey Smurf"
                        },
                        new
                        {
                            Id = new Guid("11223344-5566-4777-8899-aabbccddeeff"),
                            Age = 100,
                            Category = 1,
                            ImageUrl = "https://charactersdb.com/wp-content/uploads/baker-smurf-cartoon.jpg",
                            Name = "Chef Smurf"
                        },
                        new
                        {
                            Id = new Guid("ffeeddcc-bbaa-4111-9988-776655443322"),
                            Age = 102,
                            Category = 1,
                            ImageUrl = "https://charactersdb.com/wp-content/uploads/poet-smurf-cartoon.jpg",
                            Name = "Poet Smurf"
                        },
                        new
                        {
                            Id = new Guid("123e4567-e89b-42d3-a456-426614174000"),
                            Age = 100,
                            Category = 1,
                            ImageUrl = "https://charactersdb.com/wp-content/uploads/tracker-smurf-cartoon.jpg",
                            Name = "Tracker Smurf"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
